export const columns = [
	{ type: 'position' },
	{ type: 'field', field: 'solicitation.number' },
	{ type: 'field', field: 'solicitation.description' },
	{ type: 'field', field: 'solicitation.expires_on' },
	{ type: 'formula', field: 'market_value' },
	{ type: 'field', field: 'solicitation.estimated_value' },
	{ type: 'status', status: 'opportunity' },
	{ type: 'status', status: 'engineering' },
	{ type: 'status', status: 'bom' },
	{ type: 'status', status: 'purchasing' },
	{ type: 'status', status: 'labor' },
	{ type: 'status', status: 'review' },
	{ type: 'status', status: 'bid' },
	{ type: 'status', status: 'award' },
	{ type: 'field', field: 'solicitation.nsn.id', header: 'NSN' },
	{ type: 'matching_rule', status: 'matching_rule' },
	{ type: 'field', field: 'solicitation.set_aside' },
	{ type: 'field', field: 'solicitation.issued_on' },
	{ type: 'field', field: 'solicitation.quantity' },
	{ type: 'field', field: 'solicitation.quantity_units' },
	{ type: 'field', field: 'solicitation.first_article' },
	{
		type: 'field',
		field: 'solicitation.nsn.matching_nsns',
		array_selector: 'part_number',
		header: 'In-House PN'
	},
	{ type: 'field', field: 'solicitation.days_to_deliver' },
	{ type: 'link', field: 'bom_url' },
	{ type: 'field', field: 'unit_price' },
	{ type: 'link', field: 'solicitation.solicitation_url' },
	{ type: 'link', field: 'solicitation.tech_docs' },
	{ type: 'field', field: 'solicitation.price_won_at' }
];

export const nsnColumns = [
	{ type: 'position' },
	{ type: 'field', field: 'solicitation.expires_on' },
	{ type: 'field', field: 'solicitation.number' },
	{ type: 'field', field: 'solicitation.quantity' },
	{ type: 'field', field: 'unit_price' },
	{ type: 'status', status: 'bid' },
	{ type: 'status', status: 'award' },
	{ type: 'formula', field: 'market_value' },
	{ type: 'field', field: 'solicitation.set_aside' },
	{ type: 'field', field: 'solicitation.first_article' },
	{ type: 'link', field: 'bom_url' },
	{ type: 'field', field: 'solicitation.price_won_at' },
	{ type: 'status', status: 'opportunity' },
	{ type: 'status', status: 'engineering' },
	{ type: 'status', status: 'bom' },
	{ type: 'status', status: 'purchasing' },
	{ type: 'status', status: 'labor' },
	{ type: 'status', status: 'review' },
	{ type: 'field', field: 'solicitation.nsn.id', header: 'NSN' },
	{ type: 'field', field: 'solicitation.description' },
	{ type: 'field', field: 'solicitation.estimated_value' },
	{ type: 'matching_rule', status: 'matching_rule' },
	{ type: 'field', field: 'solicitation.issued_on' },
	{ type: 'field', field: 'solicitation.quantity_units' },
	{
		type: 'field',
		field: 'solicitation.nsn.matching_nsns',
		array_selector: 'part_number',
		header: 'In-House PN'
	},
	{ type: 'field', field: 'solicitation.days_to_deliver' },
	{ type: 'link', field: 'solicitation.solicitation_url' },
	{ type: 'link', field: 'solicitation.tech_docs' }
];
