// @ts-ignore
export function getColumns(pathname) {
	switch (pathname) {
		case '/sales/government/contracts-bid':
			return [
				{ type: 'position' },
				{ type: 'field', field: 'solicitation.id' },
				{ type: 'field', field: 'solicitation.description' },
				{ type: 'field', field: 'solicitation.expires_on' },
				{ type: 'status', status: 'award' },
				{ type: 'bid_partners' },
				{ type: 'formula', field: 'market_value' },
				{ type: 'field', field: 'solicitation.price_won_at' },
				{ type: 'formula', field: 'unit_price_won_at' },
				{ type: 'formula', field: 'diff_unit_price' },
				{ type: 'status', status: 'opportunity' },
				{ type: 'field', field: 'solicitation.nsn.id', header: 'NSN' },
				{
					type: 'products',
					header: 'In-House PN'
				},
				{ type: 'field', field: 'first_article_waive_requested' },
				{ type: 'field', field: 'first_article_waive_request_honored' },
				{ type: 'matching_rule', status: 'matching_rule' },
				{ type: 'status', status: 'engineering' },
				{ type: 'status', status: 'bom' },
				{ type: 'status', status: 'purchasing' },
				{ type: 'status', status: 'labor' },
				{ type: 'status', status: 'final_pricing' },
				{ type: 'status', status: 'bid' },
				{ type: 'field', field: 'solicitation.estimated_value' },
				{ type: 'set_aside', field: 'solicitation.set_aside' },
				{ type: 'field', field: 'solicitation.issued_on' },
				{ type: 'field', field: 'solicitation.quantity' },
				{ type: 'field', field: 'solicitation.quantity_units' },
				{ type: 'field', field: 'solicitation.first_article' },
				{ type: 'field', field: 'solicitation.days_to_deliver' },
				{ type: 'link', field: 'bom_url' },
				{ type: 'field', field: 'unit_price' },
				{ type: 'link', field: 'solicitation.solicitation_url' },
				{ type: 'link', field: 'solicitation.tech_docs' },
				{ type: 'field', field: 'flagged' }
			];
		default:
			return [
				{ type: 'position' },
				{ type: 'field', field: 'solicitation.id' },
				{ type: 'field', field: 'solicitation.description' },
				{ type: 'field', field: 'solicitation.expires_on' },
				{ type: 'formula', field: 'market_value' },
				{ type: 'field', field: 'solicitation.estimated_value' },
				{ type: 'status', status: 'opportunity' },
				{ type: 'status', status: 'engineering' },
				{ type: 'status', status: 'bom' },
				{ type: 'status', status: 'purchasing' },
				{ type: 'status', status: 'labor' },
				{ type: 'status', status: 'final_pricing' },
				{ type: 'status', status: 'enter_quote' },
				{ type: 'status', status: 'bid' },
				{ type: 'status', status: 'award' },
				{ type: 'field', field: 'solicitation.nsn.id', header: 'NSN' },
				{ type: 'matching_rule', status: 'matching_rule' },
				{ type: 'set_aside', field: 'solicitation.set_aside' },
				{ type: 'field', field: 'solicitation.issued_on' },
				{ type: 'field', field: 'solicitation.quantity' },
				{ type: 'field', field: 'solicitation.quantity_units' },
				{ type: 'field', field: 'solicitation.first_article' },
				{
					type: 'products',
					header: 'In-House PN'
				},
				{ type: 'field', field: 'solicitation.days_to_deliver' },
				{ type: 'link', field: 'bom_url' },
				{ type: 'field', field: 'unit_price' },
				{ type: 'link', field: 'solicitation.solicitation_url' },
				{ type: 'link', field: 'solicitation.tech_docs' },
				{ type: 'field', field: 'solicitation.price_won_at' },
				{ type: 'formula', field: 'unit_price_won_at' },
				{ type: 'formula', field: 'diff_unit_price' },
				{ type: 'field', field: 'flagged' }
			];
	}
}
export const nsnColumns = [
	{ type: 'position' },
	{ type: 'field', field: 'solicitation.expires_on' },
	{ type: 'field', field: 'solicitation.id' },
	{ type: 'field', field: 'solicitation.quantity' },
	{ type: 'field', field: 'unit_price' },
	{ type: 'status', status: 'bid' },
	{ type: 'status', status: 'award' },
	{ type: 'bid_partners' },
	{ type: 'formula', field: 'market_value' },
	{ type: 'field', field: 'solicitation.price_won_at' },
	{ type: 'formula', field: 'unit_price_won_at' },
	{ type: 'field', field: 'solicitation.company_awarded' },
	{ type: 'field', field: 'solicitation.date_awarded' },
	{ type: 'field', field: 'bid_notes' },
	{ type: 'field', field: 'estimated_labor_minutes' },
	{ type: 'field', field: 'estimated_material_cost' },
	{ type: 'field', field: 'estimated_purchasing_days' },
	{ type: 'formula', field: 'diff_unit_price' },
	{ type: 'set_aside', field: 'solicitation.set_aside' },
	{ type: 'field', field: 'solicitation.first_article' },
	{ type: 'link', field: 'bom_url' },
	{ type: 'status', status: 'opportunity' },
	{ type: 'status', status: 'engineering' },
	{ type: 'status', status: 'bom' },
	{ type: 'status', status: 'purchasing' },
	{ type: 'status', status: 'labor' },
	{ type: 'status', status: 'final_pricing' },
	{ type: 'field', field: 'solicitation.nsn.id', header: 'NSN' },
	{ type: 'field', field: 'solicitation.description' },
	{ type: 'field', field: 'solicitation.estimated_value' },
	{
		type: 'products',
		header: 'In-House PN'
	},
	{ type: 'matching_rule', status: 'matching_rule' },
	{ type: 'field', field: 'solicitation.issued_on' },
	{ type: 'field', field: 'solicitation.quantity_units' },
	{ type: 'field', field: 'solicitation.days_to_deliver' },
	{ type: 'link', field: 'solicitation.solicitation_url' },
	{ type: 'link', field: 'solicitation.tech_docs' }
];
